/** فلسفة يمنا: خريطة شاملة لمسارات عربية RTL؛ كل رابط رئيسي يقود إلى واجهة فعلية. */
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Route, Switch } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { CurrentUserProvider } from "./contexts/CurrentUserContext";
import { ThemeProvider } from "./contexts/ThemeContext";
import { HomePage, LoginPage, SettingsPage, CreatePage, NotFoundPage } from "./pages/YemnaPages";
import { ForgotPasswordPage, OnboardingPage, ProfileDetailPage, RegisterPage, VerificationPage, WelcomePage } from "./pages/ReferenceSuite";
import { DirectoryPage, NewMessagePage } from "./pages/SocialSuite";
import { RealtimeMessagesPage, RealtimeNotificationsPage } from "./pages/RealtimePages";
import { LiveSearchPage } from "./pages/LiveSearchPage";
import { LiveExplorePage } from "./pages/LiveExplorePage";
import { LiveMediaPage } from "./pages/LiveMediaPage";
import { LiveCommunitiesPage } from "./pages/LiveCommunitiesPage";
import { AdminAccessGuard } from "./pages/AdminAccessGuard";
import { LiveDataUnavailablePage } from "./pages/LiveDataUnavailablePage";
import { LiveRelationshipsPage } from "./pages/LiveRelationshipsPage";
import { LiveProfileEditPage } from "./pages/LiveProfileEditPage";
import { LiveSupportPage } from "./pages/LiveSupportPage";
import { LiveAdminPage } from "./pages/LiveAdminPage";
import { LiveAssistantPage } from "./pages/LiveAssistantPage";

const profileCollections = ["/my-posts","/saved","/albums","/photos","/videos","/activity","/memories"];
const liveRelationshipRoutes = ["/friends", "/friend-requests", "/followers", "/following", "/people/discover", "/blocked", "/friend-suggestions", "/people/suggestions"];
const communityExplorer = ["/communities/local","/communities/governorates","/communities/universities","/communities/interests"];
const settingsDetails = ["/settings/privacy","/settings/security","/settings/sessions","/settings/notifications","/settings/data"];
const aiTools = ["/ai/post","/ai/summary","/ai/search","/ai/sentiment","/ai/recommendations","/ai/report"];
const aiExtras = ["/ai/friends","/ai/comments","/ai/classify","/ai/writer"];
const adminDetails = ["/admin","/admin/users","/admin/content","/admin/reports","/admin/groups","/admin/pages","/admin/analytics","/admin/logs","/admin/roles","/admin/system"];
const adminExtras = ["/admin/login","/admin/messages","/admin/announcement","/admin/updates","/admin/backup","/admin/maintenance","/admin/profile","/admin/user/detail","/admin/report/detail","/admin/content/review","/admin/group/detail","/admin/page/detail"];
const states = ["/states","/states/loading","/states/empty","/states/error","/states/offline","/states/no-results","/states/blocked","/states/deleted","/states/upload-image","/states/upload-video","/states/post-unavailable","/states/user-not-found"];
const liveDataUnavailableRoutes = ["/search/advanced", "/search/voice", "/discover", "/discover/map", "/discover/interests", "/reels", "/reels/view", "/reels/create", "/reels/audio", "/reels/edit", "/reels/categories", "/live", "/live/view", "/live/create", "/live/info", "/live/active", "/live/previous"];
function Router() { return <Switch>
  <Route path="/" component={HomePage}/><Route path="/welcome" component={WelcomePage}/><Route path="/onboarding" component={OnboardingPage}/><Route path="/login" component={LoginPage}/><Route path="/register" component={RegisterPage}/><Route path="/verification" component={VerificationPage}/><Route path="/forgot-password" component={ForgotPasswordPage}/>
  <Route path="/profile/edit" component={LiveProfileEditPage}/><Route path="/profile/:username" component={ProfileDetailPage}/><Route path="/profile" component={ProfileDetailPage}/>{profileCollections.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}
  <Route path="/story/create" component={LiveDataUnavailablePage}/><Route path="/story/archive" component={LiveDataUnavailablePage}/><Route path="/story/:id" component={LiveDataUnavailablePage}/><Route path="/story" component={LiveDataUnavailablePage}/><Route path="/post/options" component={LiveDataUnavailablePage}/><Route path="/post/report" component={LiveDataUnavailablePage}/><Route path="/post/:id" component={LiveDataUnavailablePage}/><Route path="/share" component={LiveDataUnavailablePage}/><Route path="/create" component={CreatePage}/><Route path="/create/post" component={LiveDataUnavailablePage}/><Route path="/create/media" component={LiveDataUnavailablePage}/><Route path="/media/editor" component={LiveDataUnavailablePage}/><Route path="/create/video" component={LiveDataUnavailablePage}/>
  <Route path="/friends/mutual" component={LiveDataUnavailablePage}/><Route path="/friendship/manage" component={LiveDataUnavailablePage}/><Route path="/blocked/unblock" component={LiveDataUnavailablePage}/>{liveRelationshipRoutes.map(path=><Route key={path} path={path} component={LiveRelationshipsPage}/>)}<Route path="/messages/new" component={NewMessagePage}/><Route path="/messages" component={RealtimeMessagesPage}/><Route path="/messages/chat" component={LiveDataUnavailablePage}/><Route path="/messages/info" component={LiveDataUnavailablePage}/><Route path="/messages/group" component={LiveDataUnavailablePage}/><Route path="/messages/group/create" component={LiveDataUnavailablePage}/><Route path="/calls" component={LiveDataUnavailablePage}/><Route path="/call/incoming" component={LiveDataUnavailablePage}/><Route path="/call/active" component={LiveDataUnavailablePage}/><Route path="/notifications" component={RealtimeNotificationsPage}/><Route path="/notifications/settings" component={LiveDataUnavailablePage}/>
  <Route path="/groups" component={DirectoryPage}/><Route path="/groups/create" component={LiveDataUnavailablePage}/><Route path="/pages" component={LiveDataUnavailablePage}/><Route path="/pages/create" component={LiveDataUnavailablePage}/><Route path="/pages/manage" component={LiveDataUnavailablePage}/><Route path="/communities" component={LiveCommunitiesPage}/>{communityExplorer.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}<Route path="/communities/nearby" component={LiveDataUnavailablePage}/><Route path="/communities/notifications" component={LiveDataUnavailablePage}/><Route path="/communities/search" component={LiveDataUnavailablePage}/><Route path="/communities/location" component={LiveDataUnavailablePage}/><Route path="/community/old-sanaa" component={LiveDataUnavailablePage}/><Route path="/community/sanaa" component={LiveDataUnavailablePage}/><Route path="/community/page" component={LiveDataUnavailablePage}/><Route path="/page/yemna" component={LiveDataUnavailablePage}/><Route path="/community/create" component={LiveDataUnavailablePage}/><Route path="/community/join" component={LiveDataUnavailablePage}/><Route path="/community/members" component={LiveDataUnavailablePage}/><Route path="/community/manage" component={LiveDataUnavailablePage}/><Route path="/community/info" component={LiveDataUnavailablePage}/>
  <Route path="/search" component={LiveSearchPage}/><Route path="/explore" component={LiveExplorePage}/>{liveDataUnavailableRoutes.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}<Route path="/media" component={LiveMediaPage}/>
  <Route path="/events" component={LiveDataUnavailablePage}/><Route path="/events/1" component={LiveDataUnavailablePage}/><Route path="/events/create" component={LiveDataUnavailablePage}/><Route path="/files" component={LiveDataUnavailablePage}/><Route path="/help" component={LiveSupportPage}/><Route path="/help/report" component={LiveSupportPage}/><Route path="/help/report/status" component={LiveSupportPage}/><Route path="/support/reports" component={LiveSupportPage}/><Route path="/help/faq" component={LiveDataUnavailablePage}/><Route path="/help/contact" component={LiveDataUnavailablePage}/><Route path="/account" component={LiveDataUnavailablePage}/><Route path="/account/info" component={LiveDataUnavailablePage}/><Route path="/account/edit" component={LiveDataUnavailablePage}/><Route path="/account/contact/email" component={LiveDataUnavailablePage}/><Route path="/account/contact/phone" component={LiveDataUnavailablePage}/><Route path="/account/recovery" component={LiveDataUnavailablePage}/><Route path="/account/disable" component={LiveDataUnavailablePage}/><Route path="/account/delete" component={LiveDataUnavailablePage}/><Route path="/more" component={LiveDataUnavailablePage}/><Route path="/settings" component={SettingsPage}/>{settingsDetails.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>) }
  <Route path="/ai" component={LiveDataUnavailablePage}/><Route path="/ai/assistant" component={LiveAssistantPage}/>{aiTools.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}{aiExtras.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}
  <Route path="/admin" component={LiveAdminPage}/><Route path="/admin/users" component={LiveAdminPage}/><Route path="/admin/tickets" component={LiveAdminPage}/><Route path="/admin/reports" component={LiveAdminPage}/><Route path="/admin/ai-analytics" component={AdminAccessGuard}/>{adminDetails.filter(path=>!["/admin","/admin/users","/admin/reports"].includes(path)).map(path=><Route key={path} path={path} component={AdminAccessGuard}/>)}{adminExtras.map(path=><Route key={path} path={path} component={AdminAccessGuard}/>)}{states.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}<Route component={NotFoundPage}/>
</Switch>; }
export default function App() { return <ErrorBoundary><ThemeProvider defaultTheme="light" switchable><TooltipProvider><CurrentUserProvider><Toaster richColors position="top-center"/><Router/></CurrentUserProvider></TooltipProvider></ThemeProvider></ErrorBoundary>; }
