/** فلسفة يمنا: خريطة شاملة لمسارات عربية RTL؛ كل رابط رئيسي يقود إلى واجهة فعلية. */
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Route, Switch } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { CurrentUserProvider } from "./contexts/CurrentUserContext";
import { ThemeProvider } from "./contexts/ThemeContext";
import { HomePage, LoginPage, FriendsPage, MediaPage, SettingsPage, CreatePage, NotFoundPage } from "./pages/YemnaPages";
import { CreateMediaPage, CreatePostDetailPage, CreateStoryPage, EditProfilePage, ForgotPasswordPage, ImageEditorPage, OnboardingPage, PostDetailPage, PostOptionsPage, ProfileCollectionPage, ProfileDetailPage, RegisterPage, ReportPostPage, StoryArchivePage, StoryPage, UploadVideoPage, VerificationPage, WelcomePage } from "./pages/ReferenceSuite";
import { CallHistoryPage, CallPage, ChatDetailPage, ChatInfoPage, CommunityDetailPage, CommunityExplorerPage, CommunityInfoPage, CommunityManagePage, CommunityMembersPage, CreateGroupChatPage, DirectoryPage, FriendSuggestionsPage, GroupChatPage, InboxDetailPage, JoinCommunityPage, NearbyCommunityPage, NewMessagePage, NotificationDetailPage, NotificationSettingsPage, PageManagementPage, RelationsDetailPage } from "./pages/SocialSuite";
import { AdvancedSearchPage, DiscoverMapPage, DiscoverPage, InterestsPage, LiveCreatePage, LivePage, LiveViewerPage, ReelCreatePage, ReelsAudioPage, ReelsPage, ReelViewerPage, SearchDetailPage, SettingsDetailPage, StatesDetailPage, VoiceSearchPage } from "./pages/ExploreSuite";
import { AdminDetailPage, AIHubPage, AIToolDetailPage } from "./pages/AdminAISuite";
import { AdminExtraPage, CommunityExtraPage, EventsPage, ExtraAIPage, LibraryUtilityPage, MediaExtraPage, MorePage } from "./pages/GapClosureSuite";
import { AIUsageAnalyticsPage, AccountSuitePage, RelationsCompletionPage, SupportSuitePage } from "./pages/CompletionSuite";
import { PrivateProfileCollectionsPage } from "./pages/PrivateProfileCollectionsPage";
import { RealtimeMessagesPage, RealtimeNotificationsPage } from "./pages/RealtimePages";
import { LiveSearchPage } from "./pages/LiveSearchPage";
import { LiveCommunitiesPage } from "./pages/LiveCommunitiesPage";
import { AdminAccessGuard } from "./pages/AdminAccessGuard";
import { LiveDataUnavailablePage } from "./pages/LiveDataUnavailablePage";

const profileCollections = ["/my-posts","/saved","/albums","/photos","/videos","/activity","/memories"];
const profileCollectionsWithoutLiveData = profileCollections;
const relationRoutes = ["/blocked","/friend-requests","/followers","/following","/people/discover"];
const communityExplorer = ["/communities/local","/communities/governorates","/communities/universities","/communities/interests"];
const settingsDetails = ["/settings/privacy","/settings/security","/settings/sessions","/settings/notifications","/settings/data"];
const aiTools = ["/ai/assistant","/ai/post","/ai/summary","/ai/search","/ai/sentiment","/ai/recommendations","/ai/report"];
const aiExtras = ["/ai/friends","/ai/comments","/ai/classify","/ai/writer"];
const adminDetails = ["/admin","/admin/users","/admin/content","/admin/reports","/admin/groups","/admin/pages","/admin/analytics","/admin/logs","/admin/roles","/admin/system"];
const adminExtras = ["/admin/login","/admin/messages","/admin/announcement","/admin/updates","/admin/backup","/admin/maintenance","/admin/profile","/admin/user/detail","/admin/report/detail","/admin/content/review","/admin/group/detail","/admin/page/detail"];
const states = ["/states","/states/loading","/states/empty","/states/error","/states/offline","/states/no-results","/states/blocked","/states/deleted","/states/upload-image","/states/upload-video","/states/post-unavailable","/states/user-not-found"];
const liveDataUnavailableRoutes = ["/search/advanced", "/search/voice", "/discover", "/discover/map", "/discover/interests", "/reels", "/reels/view", "/reels/create", "/reels/audio", "/reels/edit", "/reels/categories", "/live", "/live/view", "/live/create", "/live/info", "/live/active", "/live/previous"];
function Router() { return <Switch>
  <Route path="/" component={HomePage}/><Route path="/welcome" component={WelcomePage}/><Route path="/onboarding" component={OnboardingPage}/><Route path="/login" component={LoginPage}/><Route path="/register" component={RegisterPage}/><Route path="/verification" component={VerificationPage}/><Route path="/forgot-password" component={ForgotPasswordPage}/>
  <Route path="/profile/edit" component={EditProfilePage}/><Route path="/profile/:username" component={ProfileDetailPage}/><Route path="/profile" component={ProfileDetailPage}/>{profileCollections.map(path=><Route key={path} path={path} component={profileCollectionsWithoutLiveData.includes(path) ? PrivateProfileCollectionsPage : ProfileCollectionPage}/>)}
  <Route path="/story/create" component={CreateStoryPage}/><Route path="/story/archive" component={StoryArchivePage}/><Route path="/story/:id" component={StoryPage}/><Route path="/story" component={StoryPage}/><Route path="/post/options" component={PostOptionsPage}/><Route path="/post/report" component={ReportPostPage}/><Route path="/post/:id" component={PostDetailPage}/><Route path="/share" component={LibraryUtilityPage}/><Route path="/create" component={CreatePage}/><Route path="/create/post" component={CreatePostDetailPage}/><Route path="/create/media" component={CreateMediaPage}/><Route path="/media/editor" component={ImageEditorPage}/><Route path="/create/video" component={UploadVideoPage}/>
  <Route path="/friends" component={FriendsPage}/><Route path="/friends/mutual" component={LiveDataUnavailablePage}/><Route path="/friendship/manage" component={LiveDataUnavailablePage}/><Route path="/blocked/unblock" component={LiveDataUnavailablePage}/><Route path="/blocked" component={LiveDataUnavailablePage}/>{relationRoutes.filter(path=>path!=="/blocked").map(path=><Route key={path} path={path} component={RelationsDetailPage}/>)}<Route path="/friend-suggestions" component={FriendSuggestionsPage}/><Route path="/people/suggestions" component={FriendSuggestionsPage}/><Route path="/messages/new" component={NewMessagePage}/><Route path="/messages" component={RealtimeMessagesPage}/><Route path="/messages/chat" component={LiveDataUnavailablePage}/><Route path="/messages/info" component={LiveDataUnavailablePage}/><Route path="/messages/group" component={LiveDataUnavailablePage}/><Route path="/messages/group/create" component={LiveDataUnavailablePage}/><Route path="/calls" component={LiveDataUnavailablePage}/><Route path="/call/incoming" component={LiveDataUnavailablePage}/><Route path="/call/active" component={LiveDataUnavailablePage}/><Route path="/notifications" component={RealtimeNotificationsPage}/><Route path="/notifications/settings" component={LiveDataUnavailablePage}/>
  <Route path="/groups" component={DirectoryPage}/><Route path="/groups/create" component={LiveDataUnavailablePage}/><Route path="/pages" component={DirectoryPage}/><Route path="/pages/create" component={LiveDataUnavailablePage}/><Route path="/pages/manage" component={LiveDataUnavailablePage}/><Route path="/communities" component={LiveCommunitiesPage}/>{communityExplorer.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}<Route path="/communities/nearby" component={LiveDataUnavailablePage}/><Route path="/communities/notifications" component={LiveDataUnavailablePage}/><Route path="/communities/search" component={LiveDataUnavailablePage}/><Route path="/communities/location" component={LiveDataUnavailablePage}/><Route path="/community/old-sanaa" component={LiveDataUnavailablePage}/><Route path="/community/sanaa" component={LiveDataUnavailablePage}/><Route path="/community/page" component={LiveDataUnavailablePage}/><Route path="/page/yemna" component={LiveDataUnavailablePage}/><Route path="/community/create" component={LiveDataUnavailablePage}/><Route path="/community/join" component={LiveDataUnavailablePage}/><Route path="/community/members" component={LiveDataUnavailablePage}/><Route path="/community/manage" component={LiveDataUnavailablePage}/><Route path="/community/info" component={LiveDataUnavailablePage}/>
  <Route path="/search" component={LiveSearchPage}/>{liveDataUnavailableRoutes.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>)}<Route path="/media" component={MediaPage}/>
  <Route path="/events" component={LiveDataUnavailablePage}/><Route path="/events/1" component={LiveDataUnavailablePage}/><Route path="/events/create" component={LiveDataUnavailablePage}/><Route path="/files" component={LiveDataUnavailablePage}/><Route path="/help" component={LiveDataUnavailablePage}/><Route path="/help/faq" component={LiveDataUnavailablePage}/><Route path="/help/report" component={LiveDataUnavailablePage}/><Route path="/help/report/status" component={LiveDataUnavailablePage}/><Route path="/help/contact" component={LiveDataUnavailablePage}/><Route path="/account" component={LiveDataUnavailablePage}/><Route path="/account/info" component={LiveDataUnavailablePage}/><Route path="/account/edit" component={LiveDataUnavailablePage}/><Route path="/account/contact/email" component={LiveDataUnavailablePage}/><Route path="/account/contact/phone" component={LiveDataUnavailablePage}/><Route path="/account/recovery" component={LiveDataUnavailablePage}/><Route path="/account/disable" component={LiveDataUnavailablePage}/><Route path="/account/delete" component={LiveDataUnavailablePage}/><Route path="/more" component={MorePage}/><Route path="/settings" component={SettingsPage}/>{settingsDetails.map(path=><Route key={path} path={path} component={LiveDataUnavailablePage}/>) }
  <Route path="/ai" component={AIHubPage}/>{aiTools.map(path=><Route key={path} path={path} component={AIToolDetailPage}/>)}{aiExtras.map(path=><Route key={path} path={path} component={ExtraAIPage}/>)}
  <Route path="/admin/ai-analytics" component={AdminAccessGuard}/>{adminDetails.map(path=><Route key={path} path={path} component={AdminAccessGuard}/>)}{adminExtras.map(path=><Route key={path} path={path} component={AdminAccessGuard}/>)}{states.map(path=><Route key={path} path={path} component={StatesDetailPage}/>)}<Route component={NotFoundPage}/>
</Switch>; }
export default function App() { return <ErrorBoundary><ThemeProvider defaultTheme="light" switchable><TooltipProvider><CurrentUserProvider><Toaster richColors position="top-center"/><Router/></CurrentUserProvider></TooltipProvider></ThemeProvider></ErrorBoundary>; }
