/** فلسفة يمنا: إغلاق النواقص المتبقية بمسارات عربية مستقلة، عملية، وواضحة على الهاتف وسطح المكتب. */
import "../completion-suite.css";
import { Link, useLocation } from "wouter";
import { useState } from "react";
import { AppShell, AdminShell } from "@/components/yemna/AppShell";
import { Avatar } from "@/components/yemna/UI";
import { people } from "@/lib/yemnaData";
import { Activity, ArrowLeft, BarChart3, Bell, Bot, BrainCircuit, Check, ChevronLeft, CircleAlert, CircleHelp, Clock3, FileQuestion, Headphones, LifeBuoy, LockKeyhole, Mail, MessageCircle, Phone, Search, Send, ShieldAlert, ShieldCheck, Sparkles, Trash2, UserRound, UserRoundCheck, UserRoundCog, UserRoundX, UsersRound, Zap } from "lucide-react";

function SuiteHead({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) {
  return <header className="completion-head">{eyebrow && <span>{eyebrow}</span>}<h1>{title}</h1>{text && <p>{text}</p>}</header>;
}

const supportEntries = [
  ["الأسئلة الشائعة", "إجابات موجزة عن الحساب والمحتوى والخصوصية.", "/help/faq", FileQuestion],
  ["الإبلاغ عن مشكلة", "أرسل بلاغاً لفريق الدعم مع تفاصيل واضحة.", "/help/report", CircleAlert],
  ["حالة البلاغ", "تابع آخر رد وتحديثات طلباتك المفتوحة.", "/help/report/status", Clock3],
  ["التواصل مع الدعم", "اختر القناة الأنسب للوصول إلى فريق يمنا.", "/help/contact", Headphones],
];

export function SupportSuitePage() {
  const [location] = useLocation();
  const mode = location.split("/").filter(Boolean).at(-1) || "help";
  const [sent, setSent] = useState(false);
  const title = mode === "faq" ? "الأسئلة الشائعة" : mode === "report" ? "الإبلاغ عن مشكلة" : mode === "status" ? "حالة البلاغات" : mode === "contact" ? "التواصل مع الدعم" : "مركز المساعدة";
  const faq = [["كيف أستعيد حسابي؟", "من شاشة الدخول اختر «نسيت كلمة المرور»، ثم اتبع رمز التحقق المرسل إليك."],["كيف أتحكم بمن يرى منشوراتي؟", "من الإعدادات والخصوصية، افتح «الخصوصية» ثم اختر جمهور المنشورات."],["كيف أبلغ عن محتوى؟", "افتح خيارات المنشور ثم اختر «إبلاغ» وحدد سبباً مناسباً."],["أين أجد بياناتي؟", "من الحساب > بياناتك يمكنك طلب نسخة من المعلومات المتاحة."]];
  return <AppShell title={title}><main className="completion-page support-suite">
    {mode === "help" && <><SuiteHead eyebrow="دعم يمنا" title="كيف يمكننا مساعدتك؟" text="ابحث عن إجابة، أرسل بلاغاً، أو تواصل مع فريق الدعم."/><div className="support-search"><Search/><input aria-label="بحث في المساعدة" placeholder="ابحث في المساعدة"/></div><section className="support-grid">{supportEntries.map(([label, text, href, Icon])=>{const I=Icon as typeof CircleHelp;return <Link href={href as string} key={label as string}><i><I/></i><strong>{label as string}</strong><p>{text as string}</p><ChevronLeft/></Link>})}</section><div className="support-note"><LifeBuoy/><div><strong>هل حسابك في خطر؟</strong><p>ابدأ من إعدادات الأمان أو تواصل معنا فوراً عند ملاحظة نشاط غير مألوف.</p></div><Link href="/settings/security">مراجعة الأمان</Link></div></>}
    {mode === "faq" && <><SuiteHead eyebrow="مركز المساعدة" title="الأسئلة الشائعة" text="إجابات مباشرة لأكثر المواضيع تداولاً."/><section className="faq-list">{faq.map(([q,a], i)=><details key={q} open={i===0}><summary><span>{q}</span><ChevronLeft/></summary><p>{a}</p></details>)}</section><div className="plain-action">لم تجد إجابتك؟ <Link href="/help/report">أرسل بلاغاً</Link></div></>}
    {mode === "report" && <div className="completion-form"><SuiteHead eyebrow="دعم يمنا" title="أخبرنا بما حدث" text="اكتب التفاصيل التي تساعد فريق الدعم على فهم المشكلة دون مشاركة بيانات حساسة."/>{sent ? <div className="success-state"><Check/><h2>تم استلام بلاغك</h2><p>رقم الطلب #Y-2048. سنرسل التحديثات إلى إشعاراتك داخل يمنا.</p><Link href="/help/report/status" className="crimson-button">عرض حالة البلاغ</Link></div> : <><label>نوع المشكلة<select defaultValue=""><option value="" disabled>اختر نوع المشكلة</option><option>الحساب وتسجيل الدخول</option><option>منشور أو رسالة</option><option>خصوصية وأمان</option><option>مشكلة تقنية</option></select></label><label>وصف المشكلة<textarea placeholder="متى بدأت المشكلة؟ وما الذي حدث؟"/></label><label>رابط أو لقطة (اختياري)<input placeholder="ألصق رابطاً أو أضف وصفاً للملف"/></label><button className="crimson-button" onClick={()=>setSent(true)}><Send/> إرسال البلاغ</button></>}</div>}
    {mode === "status" && <><SuiteHead eyebrow="دعم يمنا" title="حالة البلاغات" text="تابع البلاغات التي أرسلتها وردود فريق الدعم."/><section className="ticket-list"><article><i className="ticket-open"><Clock3/></i><div><strong>#Y-2048 · مشكلة في الإشعارات</strong><p>قيد المراجعة — آخر تحديث منذ 28 دقيقة.</p></div><span>مفتوح</span><ChevronLeft/></article><article><i className="ticket-done"><Check/></i><div><strong>#Y-1985 · استعادة الحساب</strong><p>تم الحل — تم إرسال خطوات الاستعادة.</p></div><span>مغلق</span><ChevronLeft/></article></section><Link href="/help/report" className="quiet-button">إرسال بلاغ جديد</Link></>}
    {mode === "contact" && <>{sent ? <div className="success-state"><Check/><h2>تم إرسال طلب التواصل</h2><p>أضفنا طلبك إلى صندوق الدعم، وستصلك رسالة عند رد الفريق.</p><Link href="/help/report/status" className="crimson-button">متابعة حالة الطلب</Link></div> : <><SuiteHead eyebrow="دعم يمنا" title="تواصل مع الدعم" text="اختر طريقة التواصل المناسبة حسب نوع استفسارك."/><section className="contact-cards"><button onClick={()=>setSent(true)}><Mail/><div><strong>رسالة بريدية</strong><span>متوسط الرد خلال 24 ساعة</span></div><ChevronLeft/></button><button onClick={()=>setSent(true)}><MessageCircle/><div><strong>رسائل الدعم</strong><span>متاح من داخل المنصة</span></div><ChevronLeft/></button><Link href="/help/report"><ShieldAlert/><div><strong>مشكلة أمان عاجلة</strong><span>أوقف الجلسات وابدأ بلاغاً فورياً</span></div><ChevronLeft/></Link></section></>}</>}
  </main></AppShell>;
}

const accountLinks = [
  ["معلومات الحساب", "الاسم، اسم المستخدم، وتاريخ الانضمام.", "/account/info", UserRound],
  ["تعديل البيانات", "حدّث الاسم والتعريف والصورة العامة.", "/account/edit", UserRoundCog],
  ["البريد الإلكتروني", "غيّر بريد الاسترداد وتحقق منه.", "/account/contact/email", Mail],
  ["رقم الهاتف", "أضف رقم حماية أو بدّله.", "/account/contact/phone", Phone],
  ["استعادة الحساب", "راجع وسائل الاسترداد وخطة الطوارئ.", "/account/recovery", ShieldCheck],
];

export function AccountSuitePage() {
  const [location] = useLocation();
  const mode = location.split("/").filter(Boolean).slice(1).join("/") || "overview";
  const [saved, setSaved] = useState(false);
  const title = mode === "info" ? "معلومات الحساب" : mode === "edit" ? "تعديل البيانات" : mode === "contact/email" ? "تغيير البريد الإلكتروني" : mode === "contact/phone" ? "تغيير رقم الهاتف" : mode === "recovery" ? "استعادة الحساب" : mode === "disable" ? "تعطيل الحساب" : mode === "delete" ? "حذف الحساب" : "الحساب";
  return <AppShell title={title}><main className="completion-page account-suite">
    {mode === "overview" && <><SuiteHead eyebrow="حسابك" title="إدارة معلومات حسابك" text="تحكم في بيانات التعريف، طرق الاسترداد، وخيارات حالة الحساب."/><section className="account-nav">{accountLinks.map(([label,text,href,Icon])=>{const I=Icon as typeof UserRound; return <Link href={href as string} key={label as string}><i><I/></i><div><strong>{label as string}</strong><p>{text as string}</p></div><ChevronLeft/></Link>})}</section><section className="account-danger"><div><UserRoundX/><div><strong>إيقاف أو حذف الحساب</strong><p>اختر التعطيل المؤقت أو الحذف النهائي وفق احتياجك.</p></div></div><div><Link href="/account/disable">تعطيل</Link><Link href="/account/delete">حذف الحساب</Link></div></section></>}
    {mode === "info" && <><SuiteHead eyebrow="حسابك" title="معلومات الحساب" text="بيانات التعريف الأساسية المرتبطة بحساب يمنا."/><section className="account-profile-card"><Avatar person={people[0]} size="xl"/><div><h2>عمر الحضري</h2><p>@omar_alhadrami · عضو منذ مايو 2023</p><span><ShieldCheck/> الحساب موثّق بالبريد والهاتف</span></div></section><dl className="info-list"><div><dt>البريد الإلكتروني</dt><dd>omar@example.com</dd></div><div><dt>رقم الهاتف</dt><dd>+967 77 123 4567</dd></div><div><dt>اللغة</dt><dd>العربية</dd></div><div><dt>المنطقة</dt><dd>صنعاء، اليمن</dd></div></dl></>}
    {mode === "edit" && <div className="completion-form"><SuiteHead eyebrow="ملفك" title="تعديل البيانات" text="عدّل المعلومات التي تظهر للمجتمع."/><label>الاسم<input defaultValue="عمر الحضري"/></label><label>اسم المستخدم<input defaultValue="omar_alhadrami"/></label><label>نبذة<textarea defaultValue="مهتم بالتقنية والمجتمعات المحلية."/></label><button onClick={()=>setSaved(true)} className="crimson-button">{saved ? <><Check/> تم الحفظ</> : "حفظ التغييرات"}</button></div>}
    {(mode === "contact/email" || mode === "contact/phone") && <div className="completion-form"><SuiteHead eyebrow="حماية الحساب" title={mode === "contact/email" ? "تغيير البريد الإلكتروني" : "تغيير رقم الهاتف"} text="سنطلب رمز تحقق قبل تطبيق التغيير."/><label>{mode === "contact/email" ? "البريد الجديد" : "رقم الهاتف الجديد"}<input placeholder={mode === "contact/email" ? "name@example.com" : "+967 7X XXX XXXX"}/></label><label>كلمة المرور الحالية<input type="password" placeholder="••••••••"/></label><button onClick={()=>setSaved(true)} className="crimson-button">{saved ? <><Check/> أرسلنا رمز التحقق</> : "إرسال رمز التحقق"}</button></div>}
    {mode === "recovery" && <><SuiteHead eyebrow="حماية الحساب" title="استعادة الحساب" text="حدد كيف تستعيد الوصول إذا فقدت كلمة المرور أو جهازك."/><section className="recovery-list"><article><Mail/><div><strong>البريد الإلكتروني</strong><p>omar@example.com</p></div><span>مفعّل</span></article><article><Phone/><div><strong>رقم الهاتف</strong><p>ينتهي بـ 4567</p></div><span>مفعّل</span></article><article><LockKeyhole/><div><strong>رموز الاسترداد</strong><p>احتفظ بها في مكان آمن خارج هاتفك.</p></div><button onClick={()=>setSaved(true)} className="quiet-button">{saved ? "تم إنشاء الرموز" : "إنشاء رموز"}</button></article></section></>}
    {mode === "disable" && <div className="decision-card"><UserRoundX/><SuiteHead eyebrow="إجراء قابل للعكس" title="تعطيل الحساب مؤقتاً" text="لن يظهر ملفك أو محتواك للآخرين حتى تسجل الدخول وتعيد التفعيل."/><label>سبب التعطيل<select defaultValue="استراحة"><option>استراحة مؤقتة</option><option>الخصوصية</option><option>سبب آخر</option></select></label><button onClick={()=>setSaved(true)} className="quiet-button">{saved ? "تم إرسال تأكيد التعطيل" : "تعطيل الحساب"}</button></div>}
    {mode === "delete" && <div className="decision-card destructive"><Trash2/><SuiteHead eyebrow="إجراء نهائي" title="حذف الحساب" text="سيبدأ حذف حسابك بعد فترة الحماية. يمكنك تنزيل بياناتك قبل المتابعة."/><label>اكتب «حذف حسابي» للتأكيد<input placeholder="حذف حسابي"/></label><button onClick={()=>setSaved(true)} className="danger-button">{saved ? "تم إرسال طلب الحذف" : "متابعة الحذف"}</button></div>}
  </main></AppShell>;
}

const mutualPeople = [people[1], people[2], people[3]].filter(Boolean);
export function RelationsCompletionPage() {
  const [location] = useLocation();
  const mode = location.includes("manage") ? "manage" : location.includes("unblock") ? "unblock" : location.includes("blocked") ? "blocked" : "mutual";
  const [blocked, setBlocked] = useState(mode === "blocked" || mode === "unblock");
  const [following, setFollowing] = useState(false);
  const [removed, setRemoved] = useState(false);
  return <AppShell title={mode === "mutual" ? "الأصدقاء المشتركون" : "إدارة العلاقة"}><main className="completion-page relations-completion">
    {mode === "mutual" && <><SuiteHead eyebrow="علاقاتك" title="أصدقاء مشتركون" text="أشخاص تعرفهم أنت ومحمد الحاج، وقد يساعدونكما على بدء تواصل جديد."/><section className="mutual-hero"><Avatar person={people[0]} size="lg"/><div className="mutual-people">{mutualPeople.map(person=><Avatar key={person.id} person={person} size="md"/>)}</div><strong>3 أصدقاء مشتركون</strong></section><section className="people-list">{mutualPeople.map((person, i)=><article key={person.id}><Avatar person={person} size="lg"/><div><strong>{person.name}</strong><p>{i + 2} أصدقاء مشتركون · {i === 0 ? "يعمل في التعليم" : "يهتم بالمجتمعات"}</p></div><Link href="/profile" className="quiet-button">عرض الملف</Link></article>)}</section></>}
    {mode === "manage" && <><SuiteHead eyebrow="علاقاتك" title="إدارة العلاقة" text="اختر ما يناسب طريقة ظهور تفاعلات هذا الشخص وحالتها."/><section className="relationship-card"><Avatar person={people[1]} size="xl"/><h2>{people[1]?.name}</h2><p>{removed ? "لم تعد هذه العلاقة ضمن قائمة الأصدقاء" : "صديق منذ أغسطس 2024"}</p><div className="relationship-actions"><button onClick={()=>setFollowing(!following)}><Bell/> {following ? "تتم متابعة الإشعارات" : "متابعة الإشعارات"}</button><Link href="/friends/mutual"><UsersRound/> عرض الأصدقاء المشتركين</Link><button onClick={()=>setRemoved(true)} className="warn"><UserRoundX/> {removed ? "تمت الإزالة" : "إزالة من الأصدقاء"}</button><button onClick={()=>setBlocked(true)} className="danger-lite"><ShieldAlert/> حظر الحساب</button></div></section></>}
    {(mode === "blocked" || mode === "unblock") && <><SuiteHead eyebrow="سلامتك" title="الحسابات المحظورة" text="لن يتمكن هؤلاء الأشخاص من رؤية ملفك أو مراسلتك."/>{blocked ? <section className="blocked-card"><Avatar person={people[3]} size="lg"/><div><strong>{people[3]?.name}</strong><p>تم الحظر في 18 مايو 2025</p></div><button onClick={()=>setBlocked(false)} className="quiet-button">إلغاء الحظر</button></section> : <div className="empty-completion"><ShieldCheck/><h2>لا توجد حسابات محظورة</h2><p>ستظهر هنا الحسابات التي تمنعها من التفاعل معك.</p></div>}</>}
  </main></AppShell>;
}

const insightCards = [["8,426", "طلباً إلى أدوات الذكاء", Activity, "+18% مقارنة بالأسبوع الماضي"],["71%", "نتائج تم اعتمادها", Check, "بعد مراجعة المستخدم"],["2.4 ث", "متوسط زمن الاستجابة", Zap, "ضمن المستوى المستهدف"],["93%", "استخدام آمن", ShieldCheck, "لا يحتاج إلى تدخل"]];
export function AIUsageAnalyticsPage() {
  return <AdminShell><main className="ai-usage-page"><SuiteHead eyebrow="إدارة يمنا · الذكاء الاصطناعي" title="تحليلات استخدام الذكاء الاصطناعي" text="راقب استخدام الأدوات وجودة النتائج وإشارات السلامة دون عرض محتوى المستخدمين الخاص."/><section className="insight-grid">{insightCards.map(([value,label,Icon,note])=>{const I=Icon as typeof Activity;return <article key={label as string}><i><I/></i><strong>{value as string}</strong><span>{label as string}</span><small>{note as string}</small></article>})}</section><section className="ai-chart-grid"><article className="chart-card"><header><div><span>الاستخدام خلال 7 أيام</span><strong>طلبات الأدوات</strong></div><BarChart3/></header><div className="bar-chart">{[38,58,45,72,61,84,68].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><small>{["س","ح","ن","ث","ر","خ","ج"][i]}</small></div>)}</div></article><article className="tool-ranking"><header><div><span>أكثر الأدوات استخداماً</span><strong>حسب عدد الطلبات</strong></div><BrainCircuit/></header>{[["مساعد الكتابة", "2,610", 92],["تلخيص المحتوى", "1,884", 68],["البحث الذكي", "1,327", 49],["اقتراحات الأصدقاء", "986", 36]].map(([name,total,width])=><div className="tool-row" key={name as string}><span>{name as string}</span><b>{total as string}</b><i><em style={{width:`${width}%`}}/></i></div>)}</article></section><section className="ai-safety-panel"><Bot/><div><strong>مراقبة الجودة والسلامة</strong><p>تمت مراجعة 127 إشارة تلقائياً هذا الأسبوع، مع تحويل 4 منها إلى فريق الإشراف.</p></div><Link href="/admin/reports" className="quiet-button">فتح البلاغات <ArrowLeft/></Link></section></main></AdminShell>;
}
