/** فلسفة يمنا: شاشات تفصيلية ذات قيمة فعلية تُغلق المسارات المرجعية ولا تكتفي بروابط شكلية. */
import "../gap-closure-suite.css";
import "../reels-category-fix.css";
import { Link, useLocation } from "wouter";
import { AppShell, AdminShell } from "@/components/yemna/AppShell";
import { Avatar } from "@/components/yemna/UI";
import { useCurrentUser } from "@/contexts/CurrentUserContext";
import { asPerson } from "@/lib/api";
import { CalendarDays, Check, ChevronLeft, CircleHelp, Download, FileText, Image, MapPin, MoreHorizontal, Search, Send, ShieldCheck, Sparkles, Upload, Users, Video, XCircle } from "lucide-react";

const eventItems = [
  ["ملتقى التقنية والتعليم 2025", "الأربعاء، 21 مايو · 4:00 مساءً", "جامعة صنعاء"],
  ["جلسة حكايات من صنعاء القديمة", "السبت، 24 مايو · 6:30 مساءً", "بيت الثقافة"],
  ["ورشة: أساسيات التصوير بالموبايل", "الاثنين، 26 مايو · 5:00 مساءً", "المركز المجتمعي"],
];

function Head({ eyebrow, title, text }: { eyebrow?: string; title: string; text?: string }) {
  return <header className="gap-head">{eyebrow && <span>{eyebrow}</span>}<h1>{title}</h1>{text && <p>{text}</p>}</header>;
}

export function MorePage() { return <AppShell title="المزيد"><div className="gap-page"><Head eyebrow="مساحتك" title="كل ما تحتاجه في يمنا" text="اختصارات سريعة لإدارة نشاطك واكتشاف المجتمع."/><div className="shortcut-grid">{[["الفعاليات","/events",CalendarDays],["الملفات","/files",FileText],["المساعدة","/help",CircleHelp],["نشاطي","/activity",Check],["ذكرياتي","/memories",Image],["حسابي","/settings/data",ShieldCheck]].map(([label, href, Icon])=>{ const I=Icon as typeof CalendarDays; return <Link key={label as string} href={href as string} className="shortcut-card"><I/><strong>{label as string}</strong><ChevronLeft/></Link>;})}</div></div></AppShell>; }

export function EventsPage() { const [location] = useLocation(); const isCreate = location.endsWith("/create"), isDetail = location.endsWith("/1"); return <AppShell title="الفعاليات"><div className="gap-page">{isCreate ? <div className="form-card"><Head eyebrow="فعالية جديدة" title="شارك مجتمعك ما يحدث" text="أضف التفاصيل، المكان، والجمهور المناسب."/><label>اسم الفعالية<input placeholder="مثال: ملتقى التقنية والتعليم"/></label><label>الوصف<textarea placeholder="أخبر الناس بما ينتظرهم…"/></label><div className="form-row"><label>التاريخ<input type="date"/></label><label>الوقت<input type="time"/></label></div><label>المكان<input placeholder="أضف موقعاً أو رابطاً"/></label><button className="crimson-button"><CalendarDays/> إنشاء الفعالية</button></div> : isDetail ? <div className="event-detail"><div className="event-banner"><CalendarDays/><span>فعالية يمنا</span></div><Head eyebrow="الأربعاء، 21 مايو · 4:00 مساءً" title="ملتقى التقنية والتعليم 2025" text="لقاء مفتوح للطلاب والمطورين والمعلمين لتبادل التجارب العملية في التعليم الرقمي."/><div className="event-meta"><MapPin/> قاعة المؤتمرات — جامعة صنعاء <span>·</span><Users/> 84 مهتمًا</div><div className="action-row"><button className="crimson-button"><Check/> سأحضر</button><Link className="quiet-button" href="/events">استكشاف فعاليات أخرى</Link></div></div> : <><Head eyebrow="قريباً في مجتمعك" title="الفعاليات" text="لقاءات، ورش، وأنشطة يشارك فيها مجتمع يمنا."/><div className="event-toolbar"><div className="mini-tabs"><button className="selected">لك</button><button>هذا الأسبوع</button><button>محلية</button></div><Link href="/events/create" className="crimson-button"><CalendarDays/> إنشاء فعالية</Link></div><div className="event-list">{eventItems.map((e)=><Link href="/events/1" className="event-line" key={e[0]}><div className="date-tile"><b>21</b><small>مايو</small></div><div><strong>{e[0]}</strong><span>{e[1]}</span><small><MapPin/> {e[2]}</small></div><ChevronLeft/></Link>)}</div></>}</div></AppShell>; }

export function LibraryUtilityPage() { const [location] = useLocation(); const { currentUser, isLoading: isCurrentUserLoading } = useCurrentUser(); const currentPerson = currentUser ? asPerson(currentUser) : null; const help = location==="/help", remove = location==="/account/delete", share = location==="/share"; return <AppShell title={help?"المساعدة":remove?"حذف الحساب":share?"مشاركة":"الملفات"}><div className="gap-page">{help?<><Head eyebrow="مركز الدعم" title="كيف يمكننا مساعدتك؟" text="ابحث في الأسئلة الشائعة أو أرسل مشكلة لفريق الدعم."/><div className="search-plate"><Search/><input placeholder="ابحث في المساعدة"/></div><div className="help-grid">{["الحساب وتسجيل الدخول","الخصوصية والأمان","المحتوى والوسائط","المجموعات والمجتمعات"].map(x=><button key={x}><CircleHelp/><span>{x}</span><ChevronLeft/></button>)}</div></>:remove?<div className="danger-card"><XCircle/><Head eyebrow="إجراء حساس" title="هل تريد حذف حسابك؟" text="يمكنك بدلاً من ذلك تنزيل بياناتك أو تعطيل الحساب مؤقتًا. ستُحذف بياناتك بعد فترة الحماية الموضحة."/><label>اكتب «حذف حسابي» للتأكيد<input placeholder="حذف حسابي"/></label><button className="danger-button">متابعة الحذف</button></div>:share?<div className="form-card"><Head eyebrow="شارك من يمنا" title="إرسال منشور" text="اختر المكان الذي تريد مشاركة هذا المحتوى فيه."/><div className="share-options">{isCurrentUserLoading ? <button disabled>يجري تحميل حسابك…</button> : currentPerson ? <button><Avatar person={currentPerson} size="sm"/> صفحتك الشخصية</button> : <Link href="/login" className="quiet-button">سجّل الدخول للمشاركة</Link>}<button><Users/> مجموعة التقنية والتعليم</button><button><Send/> رسالة خاصة</button></div><button className="crimson-button">مشاركة الآن</button></div>:<><Head eyebrow="مساحتك" title="الملفات والمستندات" text="استعرض ما شاركته أو ما أرسل إليك من مجموعات ومحادثات."/><div className="library-toolbar"><button className="crimson-button"><Upload/> رفع ملف</button><button className="quiet-button"><Search/> بحث في الملفات</button></div><div className="file-grid">{[["خطة ملتقى التقنية.pdf","1.8 MB · أمس",FileText],["صور ورشة البرمجة.zip","24 MB · 12 مايو",Image],["عرض المجتمع.pptx","4.2 MB · 8 مايو",FileText]].map(([name,meta,Icon])=>{const I=Icon as typeof FileText; return <article key={name as string}><i><I/></i><strong>{name as string}</strong><small>{meta as string}</small><button><Download size={16}/> تنزيل</button></article>})}</div></>}</div></AppShell>; }

export function CommunityExtraPage() { const [location] = useLocation(); const kind = location.includes("notifications")?"إشعارات المجتمع":location.includes("search")?"البحث في المجتمعات":"المجتمعات القريبة"; return <AppShell title={kind}><div className="gap-page">{kind==="إشعارات المجتمع"?<><Head eyebrow="أحدث النشاط" title="إشعارات المجتمعات" text="تابع انضمام الأعضاء، الردود، والفعاليات الجديدة."/><div className="notice-list">{["وافق المشرف على طلب انضمامك إلى مجتمع صنعاء القديمة.","نُشر حدث جديد في مجتمع التقنية والتعليم.","علّق محمد الحاج على منشورك في المجتمع المحلي."].map((x,i)=><article key={x}><i>{i+1}</i><p>{x}<small>منذ {i+1} ساعة</small></p><MoreHorizontal/></article>)}</div></>:kind==="البحث في المجتمعات"?<><Head eyebrow="دليل يمنا" title="ابحث عن مجتمعك"/><div className="search-plate"><Search/><input placeholder="مثال: جامعة صنعاء، عدن، التصوير"/></div><div className="result-pill"><Users/> مجتمع صنعاء القديمة <button className="crimson-button">انضمام</button></div><div className="result-pill"><Users/> مجتمع المبرمجين اليمنيين <button className="crimson-button">انضمام</button></div></>:<><Head eyebrow="استكشاف محلي" title="مجتمعات قريبة منك" text="فعّل الموقع لعرض مجتمعات حيّك والفعاليات القريبة."/><div className="location-permission"><MapPin/><h3>اسمح ليمنا باستخدام موقعك</h3><p>نستخدم موقعًا تقريبيًا فقط لتحسين اقتراحاتك المحلية.</p><button className="crimson-button">السماح بالموقع</button><button className="text-button">ليس الآن</button></div></>}</div></AppShell>; }

export function MediaExtraPage() { const [location] = useLocation(); const reel = location.includes("reels"), edit = location.includes("edit"), cat = location.includes("categories"), info = location.includes("live/info"), active = location.includes("live/active"), previous = location.includes("previous"); const title = reel? edit?"تعديل Reel":cat?"فئات Reels":"Reels":"البث المباشر"; return <AppShell title={title}><div className="gap-page">{reel && edit?<div className="form-card"><Head eyebrow="مقطعك القصير" title="أنهِ Reel الخاص بك"/><div className="media-preview"><Video/><span>معاينة الفيديو</span></div><label>العنوان<input placeholder="اكتب وصفًا جذابًا"/></label><label>الفئة<select defaultValue="تعليم"><option>تعليم</option><option>ترفيه</option><option>مجتمع</option></select></label><button className="crimson-button">نشر Reel</button></div>:reel && cat?<><Head eyebrow="اكتشف المحتوى" title="فئات Reels"/><div className="category-mosaic">{["تعليم","حكايات يمنية","تقنية","طبيعة","طبخ","فنون"].map(x=><Link href="/reels/view" key={x}>{x}<ChevronLeft/></Link>)}</div></>:!reel && (info||active||previous)?<div className="live-detail"><div className="live-stage"><Video/><span>{active?"مباشر الآن":"بث من مجتمع يمنا"}</span></div><Head eyebrow={active?"LIVE · 184 يشاهدون":"اكتشف البث"} title={previous?"جلسة مراجعة تصميم يمنا":"جلسة أسئلة مع مجتمع التقنية"} text="انضم للنقاش، أرسل سؤالاً، وتابع الملخص بعد انتهاء البث."/><div className="action-row"><button className="crimson-button">{active?"إرسال تعليق":"تذكير بالبث"}</button><button className="quiet-button">مشاركة</button></div></div>:<><Head eyebrow={reel?"مقاطع ملهمة من مجتمع يمنا":"الآن وقريبًا"} title={title} text={reel?"أصوات وفئات وأفكار قصيرة تستحق المشاهدة.":"شاهد البثوث، ابدأ بثاً، أو راجع لقاءات المجتمع السابقة."}/><div className="media-extra-grid">{["تعلم مهارة في دقيقة","صنعاء من الأعلى","جلسة برمجة مباشرة","حكاية صورة قديمة"].map((x,i)=><Link key={x} href={reel?"/reels/view":"/live/view"}><div><Video/><span>{i===2&&!reel?"مباشر":""}</span></div><strong>{x}</strong><small>من مجتمع يمنا</small></Link>)}</div>{!reel&&<div className="action-row"><Link href="/live/create" className="crimson-button"><Video/> ابدأ بثًا</Link><Link href="/live/previous" className="quiet-button">البثوث السابقة</Link></div>}</>}</div></AppShell>; }

export function AdminExtraPage() { const [location] = useLocation(); const record = location.split("/").at(-1); const labels: Record<string,string>={login:"دخول الإدارة",messages:"رسائل الإدارة",announcement:"إعلان جديد",updates:"تحديثات النظام",backup:"النسخ الاحتياطي",maintenance:"وضع الصيانة",profile:"الملف الإداري",detail:"تفاصيل السجل",review:"مراجعة المحتوى"}; const label=labels[record||""]||"عملية إدارية"; return <AdminShell><section className="admin-extra"><Head eyebrow="إدارة يمنا" title={label} text="مساحة تشغيلية آمنة لإدارة المجتمع واتخاذ الإجراءات المناسبة."/>{record==="login"?<div className="admin-login-card"><ShieldCheck/><h2>تحقق من صلاحيتك</h2><input placeholder="البريد الإداري"/><input placeholder="رمز التحقق"/><button className="crimson-button">دخول آمن</button></div>:record==="backup"?<div className="admin-operation"><Download/><h3>آخر نسخة احتياطية ناجحة</h3><p>19 مايو 2025 · 03:00 ص · جميع بيانات التشغيل مشفرة.</p><button className="crimson-button">إنشاء نسخة الآن</button></div>:record==="maintenance"?<div className="admin-operation"><ShieldCheck/><h3>وضع الصيانة غير مفعل</h3><p>أبلغ المستخدمين قبل تفعيل الصيانة المجدولة.</p><button className="quiet-button">جدولة صيانة</button></div>:<div className="admin-table-lite">{["مراجعة حساب: محمد الحاج","بلاغ رقم #8021","تحديث سياسة المحتوى","رسالة من مدير المجتمع"].map((x,i)=><article key={x}><span>{i+1}</span><div><strong>{x}</strong><small>محدّث منذ {i+1} ساعة</small></div><button className="quiet-button">فتح</button></article>)}</div>}</section></AdminShell>; }

export function ExtraAIPage() { const [location] = useLocation(); const mode=location.split("/").at(-1); const data:Record<string,[string,string,string]>={friends:["اقتراح أصدقاء","اكتشف علاقات مناسبة","حلّل الاهتمامات العامة والمجتمعات المشتركة للحصول على اقتراحات مفيدة."],comments:["فلترة التعليقات","حافظ على حوار صحي","راجع التعليقات قبل النشر واقترح إجراءً مناسبًا."],classify:["تصنيف المحتوى","رتّب المحتوى بذكاء","حدّد نوع المحتوى ووسومه المقترحة لتسهيل اكتشافه."],writer:["مساعد الكتابة","اكتب بوضوح وبصوتك","حوّل فكرتك إلى منشور موجز ومناسب لجمهورك."]}; const [eyebrow,title,text]=data[mode||""]||data.writer; return <AppShell title="ذكاء يمنا"><div className="gap-page ai-extra"><Head eyebrow={eyebrow} title={title} text={text}/><div className="ai-work-card"><Sparkles/><textarea placeholder="اكتب ما تريد أن يساعدك فيه ذكاء يمنا…"/><div><span>النتائج تخضع لمراجعتك قبل الاستخدام</span><button className="crimson-button">إنشاء النتيجة</button></div></div></div></AppShell>; }
